apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  labels:
    type: local
    app: elasticsearch
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/elasticsearch
  # For cloud provider, remove hostPath and use appropriate provisioner (e.g. awsElasticBlockStore, gcePersistentDisk)
  # and set storageClassName to e.g. gp2 or standard
  persistentVolumeReclaimPolicy: Retain
