apiVersion: v1
kind: PersistentVolume
metadata:
  name: kurrentdb-pv-data
  labels:
    type: local
    app: kurrentdb
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/kurrentdb/data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kurrentdb-pv-logs
  labels:
    type: local
    app: kurrentdb
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/kurrentdb/logs
  persistentVolumeReclaimPolicy: Retain
