apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kurrentdb-data-kurrentdb-0
  labels:
    app: kurrentdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kurrentdb-logs-kurrentdb-0
  labels:
    app: kurrentdb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
