serviceName: core_service
appEnv: prod
apiVersion: "api/v1"

grpc:
  port: :5001
  development: true

http:
  port: 5010
  development: false
  basePath: /api/v1
  ordersPath: /api/v1/orders
  debugErrorsResponse: true
  ignoreLogUrls: [ "metrics" ]
  sslCertPath: ""
  sslCertKey: ""

probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3001
  pprof: :6001
  prometheusPath: /metrics
  prometheusPort: :8002
  checkIntervalSeconds: 10

logger:
  level: error
  devMode: false
  encoder: console

postgres:
  host: postgresql
  port: 5432
  user: postgres
  password: 123456
  defaultDb: hype-project
  maxConnections: 1000

mongo:
  uri: "mongodb://admin:admin@mongodb:27017/orders?authSource=admin"
  user: admin
  password: admin
  db: orders

mongoCollections:
  orders: orders

eventStoreConfig:
  connectionString: "esdb://kurrentdb.db:2113?tls=false&gossipTimeout=20"

subscriptions:
  poolSize: 60
  orderPrefix: "order-"
  postgresProjectionGroupName: "order1"
  elasticProjectionGroupName: "order-elastic"

elastic:
  url: "http://node01:9200"
  sniff: false
  gzip: true
  explain: true
  fetchSource: true
  version: true
  pretty: true

elasticIndexes:
  orders: "orders"

otelCollector:
  Host: "otel-collector"
  Port: "4317"