// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: order.proto

package orderService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Payment) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ShopItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Quantity      uint64                 `protobuf:"varint,4,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItem) Reset() {
	*x = ShopItem{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItem) ProtoMessage() {}

func (x *ShopItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItem.ProtoReflect.Descriptor instead.
func (*ShopItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *ShopItem) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ShopItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShopItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShopItem) GetQuantity() uint64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ShopItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Order struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ID                string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ShopItems         []*ShopItem            `protobuf:"bytes,2,rep,name=ShopItems,proto3" json:"ShopItems,omitempty"`
	Paid              bool                   `protobuf:"varint,3,opt,name=Paid,proto3" json:"Paid,omitempty"`
	Submitted         bool                   `protobuf:"varint,4,opt,name=Submitted,proto3" json:"Submitted,omitempty"`
	Completed         bool                   `protobuf:"varint,5,opt,name=Completed,proto3" json:"Completed,omitempty"`
	Canceled          bool                   `protobuf:"varint,6,opt,name=Canceled,proto3" json:"Canceled,omitempty"`
	TotalPrice        float64                `protobuf:"fixed64,7,opt,name=TotalPrice,proto3" json:"TotalPrice,omitempty"`
	AccountEmail      string                 `protobuf:"bytes,8,opt,name=AccountEmail,proto3" json:"AccountEmail,omitempty"`
	CancelReason      string                 `protobuf:"bytes,9,opt,name=CancelReason,proto3" json:"CancelReason,omitempty"`
	DeliveryAddress   string                 `protobuf:"bytes,10,opt,name=DeliveryAddress,proto3" json:"DeliveryAddress,omitempty"`
	DeliveryTimestamp *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=DeliveryTimestamp,proto3" json:"DeliveryTimestamp,omitempty"`
	Payment           *Payment               `protobuf:"bytes,12,opt,name=Payment,proto3" json:"Payment,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Order) GetShopItems() []*ShopItem {
	if x != nil {
		return x.ShopItems
	}
	return nil
}

func (x *Order) GetPaid() bool {
	if x != nil {
		return x.Paid
	}
	return false
}

func (x *Order) GetSubmitted() bool {
	if x != nil {
		return x.Submitted
	}
	return false
}

func (x *Order) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Order) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

func (x *Order) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetAccountEmail() string {
	if x != nil {
		return x.AccountEmail
	}
	return ""
}

func (x *Order) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *Order) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *Order) GetDeliveryTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveryTimestamp
	}
	return nil
}

func (x *Order) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type CreateOrderReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountEmail    string                 `protobuf:"bytes,1,opt,name=AccountEmail,proto3" json:"AccountEmail,omitempty"`
	ShopItems       []*ShopItem            `protobuf:"bytes,2,rep,name=ShopItems,proto3" json:"ShopItems,omitempty"`
	DeliveryAddress string                 `protobuf:"bytes,3,opt,name=DeliveryAddress,proto3" json:"DeliveryAddress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderReq) GetAccountEmail() string {
	if x != nil {
		return x.AccountEmail
	}
	return ""
}

func (x *CreateOrderReq) GetShopItems() []*ShopItem {
	if x != nil {
		return x.ShopItems
	}
	return nil
}

func (x *CreateOrderReq) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

type CreateOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRes) Reset() {
	*x = CreateOrderRes{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRes) ProtoMessage() {}

func (x *CreateOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRes.ProtoReflect.Descriptor instead.
func (*CreateOrderRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderRes) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

type PayOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	Payment       *Payment               `protobuf:"bytes,2,opt,name=Payment,proto3" json:"Payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderReq) Reset() {
	*x = PayOrderReq{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderReq) ProtoMessage() {}

func (x *PayOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderReq.ProtoReflect.Descriptor instead.
func (*PayOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *PayOrderReq) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

func (x *PayOrderReq) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type PayOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderRes) Reset() {
	*x = PayOrderRes{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderRes) ProtoMessage() {}

func (x *PayOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderRes.ProtoReflect.Descriptor instead.
func (*PayOrderRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *PayOrderRes) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

type SubmitOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderReq) Reset() {
	*x = SubmitOrderReq{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderReq) ProtoMessage() {}

func (x *SubmitOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderReq.ProtoReflect.Descriptor instead.
func (*SubmitOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitOrderReq) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

type SubmitOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderRes) Reset() {
	*x = SubmitOrderRes{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRes) ProtoMessage() {}

func (x *SubmitOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRes.ProtoReflect.Descriptor instead.
func (*SubmitOrderRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitOrderRes) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

type GetOrderByIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDReq) Reset() {
	*x = GetOrderByIDReq{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDReq) ProtoMessage() {}

func (x *GetOrderByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDReq.ProtoReflect.Descriptor instead.
func (*GetOrderByIDReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderByIDReq) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

type GetOrderByIDRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=Order,proto3" json:"Order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByIDRes) Reset() {
	*x = GetOrderByIDRes{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByIDRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByIDRes) ProtoMessage() {}

func (x *GetOrderByIDRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByIDRes.ProtoReflect.Descriptor instead.
func (*GetOrderByIDRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *GetOrderByIDRes) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type UpdateShoppingCartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	ShopItems     []*ShopItem            `protobuf:"bytes,2,rep,name=ShopItems,proto3" json:"ShopItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShoppingCartReq) Reset() {
	*x = UpdateShoppingCartReq{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShoppingCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShoppingCartReq) ProtoMessage() {}

func (x *UpdateShoppingCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShoppingCartReq.ProtoReflect.Descriptor instead.
func (*UpdateShoppingCartReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateShoppingCartReq) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

func (x *UpdateShoppingCartReq) GetShopItems() []*ShopItem {
	if x != nil {
		return x.ShopItems
	}
	return nil
}

type UpdateShoppingCartRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShoppingCartRes) Reset() {
	*x = UpdateShoppingCartRes{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShoppingCartRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShoppingCartRes) ProtoMessage() {}

func (x *UpdateShoppingCartRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShoppingCartRes.ProtoReflect.Descriptor instead.
func (*UpdateShoppingCartRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

type CancelOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AggregateID   string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	CancelReason  string                 `protobuf:"bytes,2,opt,name=CancelReason,proto3" json:"CancelReason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *CancelOrderReq) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

func (x *CancelOrderReq) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

type CancelOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRes) Reset() {
	*x = CancelOrderRes{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRes) ProtoMessage() {}

func (x *CancelOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRes.ProtoReflect.Descriptor instead.
func (*CancelOrderRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

type CompleteOrderReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AggregateID       string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	DeliveryTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=DeliveryTimestamp,proto3" json:"DeliveryTimestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompleteOrderReq) Reset() {
	*x = CompleteOrderReq{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderReq) ProtoMessage() {}

func (x *CompleteOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderReq.ProtoReflect.Descriptor instead.
func (*CompleteOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *CompleteOrderReq) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

func (x *CompleteOrderReq) GetDeliveryTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveryTimestamp
	}
	return nil
}

type CompleteOrderRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOrderRes) Reset() {
	*x = CompleteOrderRes{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderRes) ProtoMessage() {}

func (x *CompleteOrderRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderRes.ProtoReflect.Descriptor instead.
func (*CompleteOrderRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

type ChangeDeliveryAddressReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AggregateID     string                 `protobuf:"bytes,1,opt,name=AggregateID,proto3" json:"AggregateID,omitempty"`
	DeliveryAddress string                 `protobuf:"bytes,2,opt,name=DeliveryAddress,proto3" json:"DeliveryAddress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangeDeliveryAddressReq) Reset() {
	*x = ChangeDeliveryAddressReq{}
	mi := &file_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeDeliveryAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDeliveryAddressReq) ProtoMessage() {}

func (x *ChangeDeliveryAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDeliveryAddressReq.ProtoReflect.Descriptor instead.
func (*ChangeDeliveryAddressReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{17}
}

func (x *ChangeDeliveryAddressReq) GetAggregateID() string {
	if x != nil {
		return x.AggregateID
	}
	return ""
}

func (x *ChangeDeliveryAddressReq) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

type ChangeDeliveryAddressRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeDeliveryAddressRes) Reset() {
	*x = ChangeDeliveryAddressRes{}
	mi := &file_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeDeliveryAddressRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDeliveryAddressRes) ProtoMessage() {}

func (x *ChangeDeliveryAddressRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDeliveryAddressRes.ProtoReflect.Descriptor instead.
func (*ChangeDeliveryAddressRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{18}
}

type SearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchText    string                 `protobuf:"bytes,1,opt,name=SearchText,proto3" json:"SearchText,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{19}
}

func (x *SearchReq) GetSearchText() string {
	if x != nil {
		return x.SearchText
	}
	return ""
}

func (x *SearchReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *Pagination            `protobuf:"bytes,1,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	Orders        []*Order               `protobuf:"bytes,2,rep,name=Orders,proto3" json:"Orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRes) Reset() {
	*x = SearchRes{}
	mi := &file_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRes) ProtoMessage() {}

func (x *SearchRes) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRes.ProtoReflect.Descriptor instead.
func (*SearchRes) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{20}
}

func (x *SearchRes) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchRes) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	TotalPages    int64                  `protobuf:"varint,2,opt,name=TotalPages,proto3" json:"TotalPages,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=HasMore,proto3" json:"HasMore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{21}
}

func (x *Pagination) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Pagination) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *Pagination) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Pagination) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\forderService\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n" +
	"\aPayment\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x128\n" +
	"\tTimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp\"\x84\x01\n" +
	"\bShopItem\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12\x1a\n" +
	"\bQuantity\x18\x04 \x01(\x04R\bQuantity\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x01R\x05Price\"\xc6\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x124\n" +
	"\tShopItems\x18\x02 \x03(\v2\x16.orderService.ShopItemR\tShopItems\x12\x12\n" +
	"\x04Paid\x18\x03 \x01(\bR\x04Paid\x12\x1c\n" +
	"\tSubmitted\x18\x04 \x01(\bR\tSubmitted\x12\x1c\n" +
	"\tCompleted\x18\x05 \x01(\bR\tCompleted\x12\x1a\n" +
	"\bCanceled\x18\x06 \x01(\bR\bCanceled\x12\x1e\n" +
	"\n" +
	"TotalPrice\x18\a \x01(\x01R\n" +
	"TotalPrice\x12\"\n" +
	"\fAccountEmail\x18\b \x01(\tR\fAccountEmail\x12\"\n" +
	"\fCancelReason\x18\t \x01(\tR\fCancelReason\x12(\n" +
	"\x0fDeliveryAddress\x18\n" +
	" \x01(\tR\x0fDeliveryAddress\x12H\n" +
	"\x11DeliveryTimestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x11DeliveryTimestamp\x12/\n" +
	"\aPayment\x18\f \x01(\v2\x15.orderService.PaymentR\aPayment\"\x94\x01\n" +
	"\x0eCreateOrderReq\x12\"\n" +
	"\fAccountEmail\x18\x01 \x01(\tR\fAccountEmail\x124\n" +
	"\tShopItems\x18\x02 \x03(\v2\x16.orderService.ShopItemR\tShopItems\x12(\n" +
	"\x0fDeliveryAddress\x18\x03 \x01(\tR\x0fDeliveryAddress\"2\n" +
	"\x0eCreateOrderRes\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\"`\n" +
	"\vPayOrderReq\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\x12/\n" +
	"\aPayment\x18\x02 \x01(\v2\x15.orderService.PaymentR\aPayment\"/\n" +
	"\vPayOrderRes\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\"2\n" +
	"\x0eSubmitOrderReq\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\"2\n" +
	"\x0eSubmitOrderRes\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\"3\n" +
	"\x0fGetOrderByIDReq\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\"<\n" +
	"\x0fGetOrderByIDRes\x12)\n" +
	"\x05Order\x18\x01 \x01(\v2\x13.orderService.OrderR\x05Order\"o\n" +
	"\x15UpdateShoppingCartReq\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\x124\n" +
	"\tShopItems\x18\x02 \x03(\v2\x16.orderService.ShopItemR\tShopItems\"\x17\n" +
	"\x15UpdateShoppingCartRes\"V\n" +
	"\x0eCancelOrderReq\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\x12\"\n" +
	"\fCancelReason\x18\x02 \x01(\tR\fCancelReason\"\x10\n" +
	"\x0eCancelOrderRes\"~\n" +
	"\x10CompleteOrderReq\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\x12H\n" +
	"\x11DeliveryTimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x11DeliveryTimestamp\"\x12\n" +
	"\x10CompleteOrderRes\"f\n" +
	"\x18ChangeDeliveryAddressReq\x12 \n" +
	"\vAggregateID\x18\x01 \x01(\tR\vAggregateID\x12(\n" +
	"\x0fDeliveryAddress\x18\x02 \x01(\tR\x0fDeliveryAddress\"\x1a\n" +
	"\x18ChangeDeliveryAddressRes\"S\n" +
	"\tSearchReq\x12\x1e\n" +
	"\n" +
	"SearchText\x18\x01 \x01(\tR\n" +
	"SearchText\x12\x12\n" +
	"\x04Page\x18\x02 \x01(\x03R\x04Page\x12\x12\n" +
	"\x04Size\x18\x03 \x01(\x03R\x04Size\"r\n" +
	"\tSearchRes\x128\n" +
	"\n" +
	"Pagination\x18\x01 \x01(\v2\x18.orderService.PaginationR\n" +
	"Pagination\x12+\n" +
	"\x06Orders\x18\x02 \x03(\v2\x13.orderService.OrderR\x06Orders\"\x8e\x01\n" +
	"\n" +
	"Pagination\x12\x1e\n" +
	"\n" +
	"TotalCount\x18\x01 \x01(\x03R\n" +
	"TotalCount\x12\x1e\n" +
	"\n" +
	"TotalPages\x18\x02 \x01(\x03R\n" +
	"TotalPages\x12\x12\n" +
	"\x04Page\x18\x03 \x01(\x03R\x04Page\x12\x12\n" +
	"\x04Size\x18\x04 \x01(\x03R\x04Size\x12\x18\n" +
	"\aHasMore\x18\x05 \x01(\bR\aHasMore2\xd5\x05\n" +
	"\forderService\x12I\n" +
	"\vCreateOrder\x12\x1c.orderService.CreateOrderReq\x1a\x1c.orderService.CreateOrderRes\x12@\n" +
	"\bPayOrder\x12\x19.orderService.PayOrderReq\x1a\x19.orderService.PayOrderRes\x12I\n" +
	"\vSubmitOrder\x12\x1c.orderService.SubmitOrderReq\x1a\x1c.orderService.SubmitOrderRes\x12^\n" +
	"\x12UpdateShoppingCart\x12#.orderService.UpdateShoppingCartReq\x1a#.orderService.UpdateShoppingCartRes\x12I\n" +
	"\vCancelOrder\x12\x1c.orderService.CancelOrderReq\x1a\x1c.orderService.CancelOrderRes\x12O\n" +
	"\rCompleteOrder\x12\x1e.orderService.CompleteOrderReq\x1a\x1e.orderService.CompleteOrderRes\x12g\n" +
	"\x15ChangeDeliveryAddress\x12&.orderService.ChangeDeliveryAddressReq\x1a&.orderService.ChangeDeliveryAddressRes\x12L\n" +
	"\fGetOrderByID\x12\x1d.orderService.GetOrderByIDReq\x1a\x1d.orderService.GetOrderByIDRes\x12:\n" +
	"\x06Search\x12\x17.orderService.SearchReq\x1a\x17.orderService.SearchResB\x11Z\x0f./;orderServiceb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_order_proto_goTypes = []any{
	(*Payment)(nil),                  // 0: orderService.Payment
	(*ShopItem)(nil),                 // 1: orderService.ShopItem
	(*Order)(nil),                    // 2: orderService.Order
	(*CreateOrderReq)(nil),           // 3: orderService.CreateOrderReq
	(*CreateOrderRes)(nil),           // 4: orderService.CreateOrderRes
	(*PayOrderReq)(nil),              // 5: orderService.PayOrderReq
	(*PayOrderRes)(nil),              // 6: orderService.PayOrderRes
	(*SubmitOrderReq)(nil),           // 7: orderService.SubmitOrderReq
	(*SubmitOrderRes)(nil),           // 8: orderService.SubmitOrderRes
	(*GetOrderByIDReq)(nil),          // 9: orderService.GetOrderByIDReq
	(*GetOrderByIDRes)(nil),          // 10: orderService.GetOrderByIDRes
	(*UpdateShoppingCartReq)(nil),    // 11: orderService.UpdateShoppingCartReq
	(*UpdateShoppingCartRes)(nil),    // 12: orderService.UpdateShoppingCartRes
	(*CancelOrderReq)(nil),           // 13: orderService.CancelOrderReq
	(*CancelOrderRes)(nil),           // 14: orderService.CancelOrderRes
	(*CompleteOrderReq)(nil),         // 15: orderService.CompleteOrderReq
	(*CompleteOrderRes)(nil),         // 16: orderService.CompleteOrderRes
	(*ChangeDeliveryAddressReq)(nil), // 17: orderService.ChangeDeliveryAddressReq
	(*ChangeDeliveryAddressRes)(nil), // 18: orderService.ChangeDeliveryAddressRes
	(*SearchReq)(nil),                // 19: orderService.SearchReq
	(*SearchRes)(nil),                // 20: orderService.SearchRes
	(*Pagination)(nil),               // 21: orderService.Pagination
	(*timestamppb.Timestamp)(nil),    // 22: google.protobuf.Timestamp
}
var file_order_proto_depIdxs = []int32{
	22, // 0: orderService.Payment.Timestamp:type_name -> google.protobuf.Timestamp
	1,  // 1: orderService.Order.ShopItems:type_name -> orderService.ShopItem
	22, // 2: orderService.Order.DeliveryTimestamp:type_name -> google.protobuf.Timestamp
	0,  // 3: orderService.Order.Payment:type_name -> orderService.Payment
	1,  // 4: orderService.CreateOrderReq.ShopItems:type_name -> orderService.ShopItem
	0,  // 5: orderService.PayOrderReq.Payment:type_name -> orderService.Payment
	2,  // 6: orderService.GetOrderByIDRes.Order:type_name -> orderService.Order
	1,  // 7: orderService.UpdateShoppingCartReq.ShopItems:type_name -> orderService.ShopItem
	22, // 8: orderService.CompleteOrderReq.DeliveryTimestamp:type_name -> google.protobuf.Timestamp
	21, // 9: orderService.SearchRes.Pagination:type_name -> orderService.Pagination
	2,  // 10: orderService.SearchRes.Orders:type_name -> orderService.Order
	3,  // 11: orderService.orderService.CreateOrder:input_type -> orderService.CreateOrderReq
	5,  // 12: orderService.orderService.PayOrder:input_type -> orderService.PayOrderReq
	7,  // 13: orderService.orderService.SubmitOrder:input_type -> orderService.SubmitOrderReq
	11, // 14: orderService.orderService.UpdateShoppingCart:input_type -> orderService.UpdateShoppingCartReq
	13, // 15: orderService.orderService.CancelOrder:input_type -> orderService.CancelOrderReq
	15, // 16: orderService.orderService.CompleteOrder:input_type -> orderService.CompleteOrderReq
	17, // 17: orderService.orderService.ChangeDeliveryAddress:input_type -> orderService.ChangeDeliveryAddressReq
	9,  // 18: orderService.orderService.GetOrderByID:input_type -> orderService.GetOrderByIDReq
	19, // 19: orderService.orderService.Search:input_type -> orderService.SearchReq
	4,  // 20: orderService.orderService.CreateOrder:output_type -> orderService.CreateOrderRes
	6,  // 21: orderService.orderService.PayOrder:output_type -> orderService.PayOrderRes
	8,  // 22: orderService.orderService.SubmitOrder:output_type -> orderService.SubmitOrderRes
	12, // 23: orderService.orderService.UpdateShoppingCart:output_type -> orderService.UpdateShoppingCartRes
	14, // 24: orderService.orderService.CancelOrder:output_type -> orderService.CancelOrderRes
	16, // 25: orderService.orderService.CompleteOrder:output_type -> orderService.CompleteOrderRes
	18, // 26: orderService.orderService.ChangeDeliveryAddress:output_type -> orderService.ChangeDeliveryAddressRes
	10, // 27: orderService.orderService.GetOrderByID:output_type -> orderService.GetOrderByIDRes
	20, // 28: orderService.orderService.Search:output_type -> orderService.SearchRes
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
